name: pybias-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  # image processing
  - scikit-image
  - scipy
  # related to jupyter notebooks
  - jupyterlab
  - ipykernel
  - stackview
  # data handling and plotting
  - pandas
  - matplotlib
  - seaborn
  # pip packages
  - pip:
    - oiffile[all]